
package com.mycompany.fos_app.GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class MainMenuGUI extends javax.swing.JFrame {


    public MainMenuGUI() {
        initComponents();
        String runnerId = SessionManager.getInstance().getidInput();
        runnerIdLB.setText(runnerId);
        currentordertxt.setEditable(false);
        locationtxt.setEditable(false);
        processDeliveryRecord(currentordertxt, locationtxt, runnerId);
    }
    
    public static void processDeliveryRecord(JTextField currentordertxt, JTextField locationtxt, String runnerId) {
        String deliveryFilePath = "src/main/java/com/mycompany/fos_app/Data/delivery.txt";
        boolean recordFound = false;

        // These variables represent your text fields, replace with your actual implementation.

        try (BufferedReader reader = new BufferedReader(new FileReader(deliveryFilePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] values = line.split(";");
                // Check that we have enough columns
                if (values.length > 4 && values[0].trim().equalsIgnoreCase(runnerId) && values[1].trim().equalsIgnoreCase("Occupied")) {
                    // Get index[2] for currentOrderTxt and index[4] for locationTxt
                    currentordertxt.setText(values[2].trim());
                    locationtxt.setText(values[4].trim());
                    recordFound = true;
                    // Assuming only one record is needed; break out of the loop.
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Handle error (e.g., show error message)
            javax.swing.JOptionPane.showMessageDialog(null, "An error occurred while processing the delivery file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!recordFound) {
        } else {
        }
    }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runnerIdLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentordertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deliveredbtn = new javax.swing.JButton();
        tasksbtn = new javax.swing.JButton();
        historybtn = new javax.swing.JButton();
        revenuebtn = new javax.swing.JButton();
        reviewbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        locationtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.lightGray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        runnerIdLB.setText("RunnerID");
        getContentPane().add(runnerIdLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel3.setText("Current Order : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 266, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel4.setText("Location : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 304, -1, -1));

        currentordertxt.setEditable(false);
        currentordertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        currentordertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentordertxtActionPerformed(evt);
            }
        });
        getContentPane().add(currentordertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 270, 101, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 47, -1, -1));

        deliveredbtn.setBackground(new java.awt.Color(204, 255, 204));
        deliveredbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deliveredbtn.setText("Delivered");
        deliveredbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deliveredbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 381, -1, -1));

        tasksbtn.setBackground(new java.awt.Color(255, 153, 51));
        tasksbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tasksbtn.setForeground(new java.awt.Color(255, 255, 255));
        tasksbtn.setText("Tasks");
        tasksbtn.setFocusPainted(false);
        tasksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tasksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 131, 118, -1));

        historybtn.setBackground(new java.awt.Color(255, 102, 102));
        historybtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        historybtn.setForeground(new java.awt.Color(255, 255, 255));
        historybtn.setText("History");
        historybtn.setFocusPainted(false);
        historybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybtnActionPerformed(evt);
            }
        });
        getContentPane().add(historybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 188, 118, -1));

        revenuebtn.setBackground(new java.awt.Color(102, 204, 255));
        revenuebtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        revenuebtn.setForeground(new java.awt.Color(255, 255, 255));
        revenuebtn.setText("Revenue");
        revenuebtn.setFocusPainted(false);
        revenuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenuebtnActionPerformed(evt);
            }
        });
        getContentPane().add(revenuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 188, -1, -1));

        reviewbtn.setBackground(new java.awt.Color(204, 153, 255));
        reviewbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reviewbtn.setForeground(new java.awt.Color(255, 255, 255));
        reviewbtn.setText("Reviews");
        reviewbtn.setFocusPainted(false);
        reviewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewbtnActionPerformed(evt);
            }
        });
        getContentPane().add(reviewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 131, 121, -1));

        logoutbtn.setBackground(new java.awt.Color(204, 204, 204));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 431, 108, -1));

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        locationtxt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deliveredbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredbtnActionPerformed
        int response = JOptionPane.showConfirmDialog(
               this, 
               "Are you sure?", 
               "Confirm Delivery", 
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE
           );

           if (response == JOptionPane.YES_OPTION) {
               RunnerTasks.completeOrder(currentordertxt);
               RunnerTasks.completeDeliveryOrder(currentordertxt);
               currentordertxt.setText("");
               locationtxt.setText("");
           }
    }//GEN-LAST:event_deliveredbtnActionPerformed

    private void tasksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksbtnActionPerformed
        this.dispose();
        TasksGUI taskpage = new TasksGUI();
        taskpage.setVisible(true);
    }//GEN-LAST:event_tasksbtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        this.dispose();
        HistoryGUI history = new HistoryGUI();
        history.setVisible(true);
    }//GEN-LAST:event_historybtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to log out?", 
                "Confirm Logout", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {
                this.dispose();
                Staff_Login login = new Staff_Login();
                login.setVisible(true);
                
            }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void reviewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewbtnActionPerformed
        this.dispose();
        ReviewGUI review = new ReviewGUI();
        review.setVisible(true);
    }//GEN-LAST:event_reviewbtnActionPerformed

    private void revenuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenuebtnActionPerformed
        this.dispose();
        RevenueGUI revenue = new RevenueGUI();
        revenue.setVisible(true);
    }//GEN-LAST:event_revenuebtnActionPerformed

    private void currentordertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentordertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentordertxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentordertxt;
    private javax.swing.JButton deliveredbtn;
    private javax.swing.JButton historybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton revenuebtn;
    private javax.swing.JButton reviewbtn;
    private javax.swing.JLabel runnerIdLB;
    private javax.swing.JButton tasksbtn;
    // End of variables declaration//GEN-END:variables
}
