/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fos_app.GUI;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class RevenueGUI extends javax.swing.JFrame {
    private DefaultTableModel model;
    private String[] columnNames = {"Order ID", "Customer Name", "Items", "Price", "Method", "Address","Phone Number", "Status", "Date", "CustomerID", "VendorID", "RiderID", "Count"};
    /**
     * Creates new form RevenueGUI
     */
    public RevenueGUI() {
        initComponents();
        String runnerId = SessionManager.getInstance().getidInput();
        setTitle("Revenue");
        updateTotalInTextField(totaltxt, runnerId);
        
        model = new DefaultTableModel(columnNames, 0);
        revenueTable.setModel(model);
        
        try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/com/mycompany/fos_app/Data/orders.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assuming the file is comma-separated.
                String[] values = line.split(";");
                // Ensure there are enough columns:
                // Check that value[11] equals "R002" and value[7] equals "Completed"
                if (values.length > 11 && values.length > 7) {
                    if (values[11].trim().equalsIgnoreCase(runnerId) &&
                        values[7].trim().equalsIgnoreCase("Completed")) {
                        model.addRow(values);
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        revenueTable.removeColumn(revenueTable.getColumn("Customer Name"));
        revenueTable.removeColumn(revenueTable.getColumn("Method"));
        revenueTable.removeColumn(revenueTable.getColumn("CustomerID"));
        revenueTable.removeColumn(revenueTable.getColumn("Count"));
        
    }
    
    private void updateTotalInTextField(JTextField totaltxt, String runnerId) {
        String ordersFilePath = "src/main/java/com/mycompany/fos_app/Data/orders.txt";
        double total = 0.0;

        try (BufferedReader br = new BufferedReader(new FileReader(ordersFilePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assuming the file is semicolon-separated.
                String[] values = line.split(";");
                // Check we have enough columns: at least index 11, 7, and 3 exist.
                if (values.length > 11 && values.length > 7 && values.length > 3) {
                    if (values[11].trim().equalsIgnoreCase(runnerId) &&
                        values[7].trim().equalsIgnoreCase("Completed")) {
                        try {
                            double amount = Double.parseDouble(values[3].trim());
                            total += amount;
                        } catch (NumberFormatException e) {
                            System.err.println("Error parsing value[3]: " + values[3]);
                        }
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Error reading orders file: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        // Set the total into the totaltxt JTextField.
        totaltxt.setText(String.valueOf(total));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        revenueTable = new javax.swing.JTable();
        totaltxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbtn2.setBackground(new java.awt.Color(204, 204, 204));
        backbtn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backbtn2.setText("Back");
        backbtn2.setFocusPainted(false);
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Revenue");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 52, -1, -1));

        revenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(revenueTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 137, 580, 312));
        getContentPane().add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 480, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Total Earnings:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel2)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        MainMenuGUI mainmenu = new MainMenuGUI();
        mainmenu.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RevenueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable revenueTable;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
